/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guicalculator;

import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.*;

/**
 *
 * @author Sanele
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        ButtonGroup bgMenuItems = new ButtonGroup();
        bgMenuItems.add(rbMnuItemWindows);
        bgMenuItems.add(rbMnuItemMotif);
        bgMenuItems.add(rbMnuItemMetal);
        
        FrmMain.this.setTitle("Calculator");
        FrmMain.this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        FrmMain.this.setResizable(false);
        
        FrmMain.this.addWindowListener(new WindowAdapter() {
           @Override
           public void windowIconified(WindowEvent we) {
               FrmMain.this.setState(ICONIFIED);
           } 
           
           @Override
            public void windowClosing(WindowEvent e) {
                if(JOptionPane.showConfirmDialog(FrmMain.this, "Would you like to exit the calculator?",
                    "Exit?", JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.YES_OPTION) {
                    
                    System.exit(0);
                }
            }
        });
        
    }
    
    Arithmetic arithmetic = new Arithmetic();
    Scientific scientific = new Scientific();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMainPanel = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        mbMenuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuItemMinimise = new javax.swing.JMenuItem();
        mnuItemClose = new javax.swing.JMenuItem();
        mnuView = new javax.swing.JMenu();
        mnuItemArithmetic = new javax.swing.JMenuItem();
        mnuItemScientific = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        mnuItemLookAndFeel = new javax.swing.JMenu();
        rbMnuItemWindows = new javax.swing.JRadioButtonMenuItem();
        rbMnuItemMotif = new javax.swing.JRadioButtonMenuItem();
        rbMnuItemMetal = new javax.swing.JRadioButtonMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpMainPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guicalculator/math-symbols.jpg"))); // NOI18N

        javax.swing.GroupLayout jpMainPanelLayout = new javax.swing.GroupLayout(jpMainPanel);
        jpMainPanel.setLayout(jpMainPanelLayout);
        jpMainPanelLayout.setHorizontalGroup(
            jpMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lblIcon)
                .addGap(150, 150, 150))
        );
        jpMainPanelLayout.setVerticalGroup(
            jpMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );

        mnuFile.setText("File");

        mnuItemMinimise.setText("Minimise");
        mnuItemMinimise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemMinimiseActionPerformed(evt);
            }
        });
        mnuFile.add(mnuItemMinimise);

        mnuItemClose.setText("Close");
        mnuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCloseActionPerformed(evt);
            }
        });
        mnuFile.add(mnuItemClose);

        mbMenuBar.add(mnuFile);

        mnuView.setText("View");

        mnuItemArithmetic.setText("Standard");
        mnuItemArithmetic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemArithmeticActionPerformed(evt);
            }
        });
        mnuView.add(mnuItemArithmetic);

        mnuItemScientific.setText("Scientific");
        mnuItemScientific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemScientificActionPerformed(evt);
            }
        });
        mnuView.add(mnuItemScientific);
        mnuView.add(separator);

        mnuItemLookAndFeel.setText("Look & Feel");

        rbMnuItemWindows.setSelected(true);
        rbMnuItemWindows.setText("Windows");
        rbMnuItemWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMnuItemWindowsActionPerformed(evt);
            }
        });
        mnuItemLookAndFeel.add(rbMnuItemWindows);

        rbMnuItemMotif.setSelected(true);
        rbMnuItemMotif.setText("Motif");
        rbMnuItemMotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMnuItemMotifActionPerformed(evt);
            }
        });
        mnuItemLookAndFeel.add(rbMnuItemMotif);

        rbMnuItemMetal.setSelected(true);
        rbMnuItemMetal.setText("Metal");
        rbMnuItemMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMnuItemMetalActionPerformed(evt);
            }
        });
        mnuItemLookAndFeel.add(rbMnuItemMetal);

        mnuView.add(mnuItemLookAndFeel);

        mbMenuBar.add(mnuView);

        mnuHelp.setText("Help");

        mnuItemAbout.setText("About");
        mnuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuItemAbout);

        mbMenuBar.add(mnuHelp);

        setJMenuBar(mbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemArithmeticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemArithmeticActionPerformed
        if(lblIcon.isShowing() || scientific.isShowing()) {
            jpMainPanel.remove(lblIcon);
            jpMainPanel.remove(scientific);
        }
        jpMainPanel.add(arithmetic, BorderLayout.CENTER);
        this.setBounds(460, 10, 440, 645);
        //SwingUtilities.updateComponentTreeUI(jpMainPanel);
        
    }//GEN-LAST:event_mnuItemArithmeticActionPerformed

    private void mnuItemScientificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemScientificActionPerformed
        if(lblIcon.isShowing() || arithmetic.isShowing()) {
            jpMainPanel.remove(lblIcon);
            jpMainPanel.remove(arithmetic);
        }
        jpMainPanel.add(scientific, BorderLayout.CENTER);
        this.setBounds(460, 10, 480, 710);
        SwingUtilities.updateComponentTreeUI(jpMainPanel);
    }//GEN-LAST:event_mnuItemScientificActionPerformed

    private void mnuItemMinimiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemMinimiseActionPerformed
        FrmMain.this.setState(ICONIFIED);
    }//GEN-LAST:event_mnuItemMinimiseActionPerformed

    private void mnuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCloseActionPerformed
        if(JOptionPane.showConfirmDialog(FrmMain.this, "Would you like to exit the calculator?",
                    "Exit?", JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
                    
        }
    }//GEN-LAST:event_mnuItemCloseActionPerformed

    private void rbMnuItemWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMnuItemWindowsActionPerformed
        try {
            UIManager.setLookAndFeel(
                    ("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"));
            SwingUtilities.updateComponentTreeUI(FrmMain.this);
                
        } catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rbMnuItemWindowsActionPerformed

    private void rbMnuItemMotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMnuItemMotifActionPerformed
        try {
            UIManager.setLookAndFeel(
                ("com.sun.java.swing.plaf.motif.MotifLookAndFeel"));
            SwingUtilities.updateComponentTreeUI(FrmMain.this);
                
        } catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rbMnuItemMotifActionPerformed

    private void rbMnuItemMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMnuItemMetalActionPerformed
        try {
            UIManager.setLookAndFeel(
                ("javax.swing.plaf.metal.MetalLookAndFeel"));
            SwingUtilities.updateComponentTreeUI(FrmMain.this);
                
        } catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rbMnuItemMetalActionPerformed

    private void mnuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAboutActionPerformed
        JDialog dialogAbout = new JDialog(FrmMain.this, "About Calculator");
            JTextArea taAboutArea = new JTextArea();
            taAboutArea.setWrapStyleWord(true);
            taAboutArea.setEditable(false);
            String strAbout = "This is a calculator application.\n"
                    + "The application has a standard and a scientific mode.\n"
                    + "As a user you have control over the app's look and feel."
                    + "\n \n"
                    + "\nDeveloped By: Sanele Manyela September/2021\n";
            taAboutArea.setText(strAbout);
            dialogAbout.add(taAboutArea);
            dialogAbout.pack();
            dialogAbout.setLocationRelativeTo(this);
            dialogAbout.setVisible(true);
    }//GEN-LAST:event_mnuItemAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpMainPanel;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JMenuBar mbMenuBar;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuItemAbout;
    private javax.swing.JMenuItem mnuItemArithmetic;
    private javax.swing.JMenuItem mnuItemClose;
    private javax.swing.JMenu mnuItemLookAndFeel;
    private javax.swing.JMenuItem mnuItemMinimise;
    private javax.swing.JMenuItem mnuItemScientific;
    private javax.swing.JMenu mnuView;
    private javax.swing.JRadioButtonMenuItem rbMnuItemMetal;
    private javax.swing.JRadioButtonMenuItem rbMnuItemMotif;
    private javax.swing.JRadioButtonMenuItem rbMnuItemWindows;
    private javax.swing.JPopupMenu.Separator separator;
    // End of variables declaration//GEN-END:variables
}
