/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guicalculator;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigInteger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanele
 */
public class Scientific extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form Scientific
     */
    public Scientific() {
        initComponents();
        this.setSize(456, 649);
        Scientific.this.txtInput.setText("0");
        
        btnZero.addActionListener(Scientific.this);
        btnOne.addActionListener(Scientific.this);
        btnTwo.addActionListener(Scientific.this);
        btnThree.addActionListener(Scientific.this);
        btnFour.addActionListener(Scientific.this);
        btnFive.addActionListener(Scientific.this);
        btnSix.addActionListener(Scientific.this);
        btnSeven.addActionListener(Scientific.this);
        btnEight.addActionListener(Scientific.this);
        btnNine.addActionListener(Scientific.this);
    }
    
    char operator;
    
    Arithmetic arithmetic = new Arithmetic();
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(btnZero)) {
            
            if(!txtInput.getText().equals("0")) {
                txtInput.setText(txtInput.getText() + btnZero.getText());
            }
            
        } else if(e.getSource().equals(btnOne)) {
            
            if(txtInput.getText().equals("0")) {
                txtInput.setText(btnOne.getText());
                
            } else {
                txtInput.setText(txtInput.getText() + btnOne.getText());
            }
            
        } else if(e.getSource().equals(btnTwo)) {
            
            if(txtInput.getText().equals("0")) {
                txtInput.setText(btnTwo.getText());
                
            } else {
                txtInput.setText(txtInput.getText() + btnTwo.getText());
            }
            
        } else if(e.getSource().equals(btnThree)) {
            
            if(txtInput.getText().equals("0")) {
                txtInput.setText(btnThree.getText());
                
            } else {
                txtInput.setText(txtInput.getText() + btnThree.getText());
            }
            
        } else if(e.getSource().equals(btnFour)) {
            
            if(txtInput.getText().equals("0")) {
                txtInput.setText(btnFour.getText());
                
            } else {
                txtInput.setText(txtInput.getText() + btnFour.getText());
            }
            
        } else if(e.getSource().equals(btnFive)) {
            
            if(txtInput.getText().equals("0")) {
                txtInput.setText(btnFive.getText());
                
            } else {
                txtInput.setText(txtInput.getText() + btnFive.getText());
            }
            
        } else if(e.getSource().equals(btnSix)) {
            
            if(txtInput.getText().equals("0")) {
                txtInput.setText(btnSix.getText());
                
            } else {
                txtInput.setText(txtInput.getText() + btnSix.getText());
            }
            
        } else if(e.getSource().equals(btnSeven)) {
            
            if(txtInput.getText().equals("0")) {
                txtInput.setText(btnSeven.getText());
                
            } else {
                txtInput.setText(txtInput.getText() + btnSeven.getText());
            }
            
        } else if(e.getSource().equals(btnEight)) {
            
            if(txtInput.getText().equals("0")) {
                txtInput.setText(btnEight.getText());
                
            } else {
                txtInput.setText(txtInput.getText() + btnEight.getText());
            }
            
        } else if(e.getSource().equals(btnNine)) {
            
            if(txtInput.getText().equals("0")) {
                txtInput.setText(btnNine.getText());
                
            } else {
                txtInput.setText(txtInput.getText() + btnNine.getText());
            }
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDisplayPane = new javax.swing.JPanel();
        txtInput = new javax.swing.JTextField();
        lblCalculation = new javax.swing.JLabel();
        jpButtonPane = new javax.swing.JPanel();
        btnPi = new javax.swing.JButton();
        btnClearEverything = new javax.swing.JButton();
        btnClearChar = new javax.swing.JButton();
        btnReciprocal = new javax.swing.JButton();
        btnSquared = new javax.swing.JButton();
        btnSquareRoot = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnMultiplication = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnAddition = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnOne = new javax.swing.JButton();
        btnPoint = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnSigns = new javax.swing.JButton();
        btnCubed = new javax.swing.JButton();
        btnXPower = new javax.swing.JButton();
        btnTenPowerX = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnFactorial = new javax.swing.JButton();
        btnTwoTimesSqrt = new javax.swing.JButton();
        btnThreeTimesSqrt = new javax.swing.JButton();
        jpTrigonometryPane = new javax.swing.JPanel();
        btnSin = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnSec = new javax.swing.JButton();
        btnCsc = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jpDisplayPane.setBackground(new java.awt.Color(255, 255, 255));

        txtInput.setEditable(false);
        txtInput.setBackground(new java.awt.Color(255, 255, 255));
        txtInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblCalculation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jpDisplayPaneLayout = new javax.swing.GroupLayout(jpDisplayPane);
        jpDisplayPane.setLayout(jpDisplayPaneLayout);
        jpDisplayPaneLayout.setHorizontalGroup(
            jpDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDisplayPaneLayout.createSequentialGroup()
                .addGroup(jpDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInput, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addComponent(lblCalculation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jpDisplayPaneLayout.setVerticalGroup(
            jpDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDisplayPaneLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCalculation, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpButtonPane.setBackground(new java.awt.Color(255, 255, 255));

        btnPi.setText("π");
        btnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiActionPerformed(evt);
            }
        });

        btnClearEverything.setText("CE");
        btnClearEverything.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearEverythingActionPerformed(evt);
            }
        });

        btnClearChar.setText("<x");
        btnClearChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCharActionPerformed(evt);
            }
        });

        btnReciprocal.setText("1/x");
        btnReciprocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReciprocalActionPerformed(evt);
            }
        });

        btnSquared.setText("x^2");
        btnSquared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquaredActionPerformed(evt);
            }
        });

        btnSquareRoot.setText("√ x");
        btnSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareRootActionPerformed(evt);
            }
        });

        btnDivision.setText("/");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnMultiplication.setText("X");
        btnMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicationActionPerformed(evt);
            }
        });

        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnAddition.setText("+");
        btnAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdditionActionPerformed(evt);
            }
        });

        btnEquals.setText("=");
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });

        btnNine.setText("9");

        btnEight.setText("8");

        btnSeven.setText("7");
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnSix.setText("6");
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        btnFive.setText("5");
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        btnFour.setText("4");
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnThree.setText("3");
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btnTwo.setText("2");
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        btnOne.setText("1");
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnPoint.setText(".");
        btnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPointActionPerformed(evt);
            }
        });

        btnZero.setText("0");

        btnSigns.setText("+/-");
        btnSigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignsActionPerformed(evt);
            }
        });

        btnCubed.setText("x^3");
        btnCubed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCubedActionPerformed(evt);
            }
        });

        btnXPower.setText("x^y");
        btnXPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXPowerActionPerformed(evt);
            }
        });

        btnTenPowerX.setText("10^x");
        btnTenPowerX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTenPowerXActionPerformed(evt);
            }
        });

        btnLog.setText("Log");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        btnFactorial.setText("n!");
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });

        btnTwoTimesSqrt.setText("2√ x");
        btnTwoTimesSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoTimesSqrtActionPerformed(evt);
            }
        });

        btnThreeTimesSqrt.setText("3√ x");
        btnThreeTimesSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeTimesSqrtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpButtonPaneLayout = new javax.swing.GroupLayout(jpButtonPane);
        jpButtonPane.setLayout(jpButtonPaneLayout);
        jpButtonPaneLayout.setHorizontalGroup(
            jpButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXPower, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTenPowerX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFactorial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSquared, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSquareRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpButtonPaneLayout.createSequentialGroup()
                        .addComponent(btnCubed, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClearEverything, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClearChar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpButtonPaneLayout.createSequentialGroup()
                        .addGroup(jpButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jpButtonPaneLayout.createSequentialGroup()
                                .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpButtonPaneLayout.createSequentialGroup()
                                .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpButtonPaneLayout.createSequentialGroup()
                                .addComponent(btnReciprocal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTwoTimesSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnThreeTimesSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpButtonPaneLayout.createSequentialGroup()
                                .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpButtonPaneLayout.createSequentialGroup()
                                .addComponent(btnSigns, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jpButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jpButtonPaneLayout.setVerticalGroup(
            jpButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonPaneLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClearChar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClearEverything, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCubed, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSquared, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReciprocal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTwoTimesSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThreeTimesSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXPower, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTenPowerX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSigns, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jpTrigonometryPane.setBackground(new java.awt.Color(255, 255, 255));

        btnSin.setText("Sin");
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });

        btnCos.setText("Cos");
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });

        btnTan.setText("Tan");
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });

        btnSec.setText("Sec");
        btnSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecActionPerformed(evt);
            }
        });

        btnCsc.setText("Csc");
        btnCsc.setToolTipText("");
        btnCsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCscActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpTrigonometryPaneLayout = new javax.swing.GroupLayout(jpTrigonometryPane);
        jpTrigonometryPane.setLayout(jpTrigonometryPaneLayout);
        jpTrigonometryPaneLayout.setHorizontalGroup(
            jpTrigonometryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTrigonometryPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSec, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCsc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTrigonometryPaneLayout.setVerticalGroup(
            jpTrigonometryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTrigonometryPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpTrigonometryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSec, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCsc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpDisplayPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jpButtonPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpTrigonometryPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpDisplayPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpTrigonometryPane, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpButtonPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiActionPerformed
        txtInput.setText(String.valueOf((Math.PI)));
    }//GEN-LAST:event_btnPiActionPerformed

    private void btnReciprocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReciprocalActionPerformed
        try {
            if(!txtInput.getText().equals("0")) {
                lblCalculation.setText("1/(" + txtInput.getText() + ") = ");
                txtInput.setText(String.valueOf(arithmetic.roundOff(1/Double.parseDouble(
                    txtInput.getText()))));
            } else {
                txtInput.setText("Cannot divide by zero");
            }
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReciprocalActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnCubedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCubedActionPerformed
        try {
            lblCalculation.setText(txtInput.getText() + " ^ 3 =");
            txtInput.setText(String.valueOf(arithmetic.roundOff(Math.pow(Double.parseDouble(
                txtInput.getText()), 3))));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCubedActionPerformed

    private void btnXPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXPowerActionPerformed
        lblCalculation.setText(txtInput.getText() + " ^ ");
        txtInput.setText("");
        operator = '^';
    }//GEN-LAST:event_btnXPowerActionPerformed

    private void btnTenPowerXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTenPowerXActionPerformed
        try {
            lblCalculation.setText("10 ^ "+txtInput.getText()+" =");
            txtInput.setText(String.valueOf(arithmetic.roundOff(Math.pow(10, Double.parseDouble(
                txtInput.getText())))));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTenPowerXActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        try {
            lblCalculation.setText("Log of " +txtInput.getText()+" =");
            txtInput.setText(String.valueOf(arithmetic.roundOff(Math.log(
                Double.parseDouble(txtInput.getText())))));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        try {
            
            BigInteger factorial = BigInteger.ONE;

            for (int i = Integer.parseInt(txtInput.getText()); i > 0; i--) {
                factorial = factorial.multiply(BigInteger.valueOf(i));
            }
                        
            lblCalculation.setText(txtInput.getText() +"! =");
            txtInput.setText(String.valueOf(factorial));
            
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter integers", "ERROR", JOptionPane.ERROR_MESSAGE);
            lblCalculation.setText("");
            txtInput.setText(String.valueOf(0));
        }
    }//GEN-LAST:event_btnFactorialActionPerformed

    private void btnSquaredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquaredActionPerformed
        try {
            lblCalculation.setText(txtInput.getText() + " ^ 2 =");
            txtInput.setText(String.valueOf(arithmetic.roundOff(Math.pow(Double.parseDouble(
                txtInput.getText()), 2))));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSquaredActionPerformed

    private void btnClearEverythingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearEverythingActionPerformed
        lblCalculation.setText("");
        txtInput.setText("");
    }//GEN-LAST:event_btnClearEverythingActionPerformed

    private void btnClearCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCharActionPerformed
        try {
            txtInput.setText(txtInput.getText().substring(0, txtInput.getText().length() - 1));
        } catch(StringIndexOutOfBoundsException e) {
        }
    }//GEN-LAST:event_btnClearCharActionPerformed

    private void btnSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareRootActionPerformed
        try {
            lblCalculation.setText("Sqrt("+ txtInput.getText() +") =");
            txtInput.setText(String.valueOf(arithmetic.roundOff(Math.sqrt(Double.parseDouble(
                txtInput.getText())))));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSquareRootActionPerformed

    private void btnTwoTimesSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoTimesSqrtActionPerformed
        try {
            lblCalculation.setText("2 * Sqrt("+ txtInput.getText() +") =");
            txtInput.setText(String.valueOf(arithmetic.roundOff(2 * Math.sqrt(Double.parseDouble(
                txtInput.getText())))));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTwoTimesSqrtActionPerformed

    private void btnThreeTimesSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeTimesSqrtActionPerformed
        try {
            lblCalculation.setText("3 * Sqrt("+ txtInput.getText() +") =");
            txtInput.setText(String.valueOf(arithmetic.roundOff(3 * Math.sqrt(Double.parseDouble(
                txtInput.getText())))));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThreeTimesSqrtActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        lblCalculation.setText(txtInput.getText() + " / ");
        txtInput.setText("");
        operator = '/';
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicationActionPerformed
        lblCalculation.setText(txtInput.getText() + " * ");
        txtInput.setText("");
        operator = '*';
    }//GEN-LAST:event_btnMultiplicationActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        lblCalculation.setText(txtInput.getText() + " - ");
        txtInput.setText("");
        operator = '-';
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdditionActionPerformed
        lblCalculation.setText(txtInput.getText() + " + ");
        txtInput.setText("");
        operator = '+';
    }//GEN-LAST:event_btnAdditionActionPerformed

    private void btnSignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignsActionPerformed
        String strInput = txtInput.getText();
        
        if(strInput.contains(".")) {
            txtInput.setText(String.valueOf(arithmetic.roundOff(Double.parseDouble(strInput) * -1)));
        } else {
            try {
                txtInput.setText(String.valueOf(Integer.parseInt(strInput) * -1));
            } catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSignsActionPerformed

    private void btnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPointActionPerformed
        txtInput.setText(txtInput.getText() + ".");
    }//GEN-LAST:event_btnPointActionPerformed

    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
        try {
            lblCalculation.setText(lblCalculation.getText() + txtInput.getText());
        
            int index = lblCalculation.getText().indexOf(" ");
            double x = Double.parseDouble(lblCalculation.getText().substring(0,
                        index).trim());
        
            String[] str = lblCalculation.getText().split(" ");
        
            double y = Double.parseDouble(str[str.length - 1]);
        
            lblCalculation.setText(lblCalculation.getText() + " = ");
        
            switch(operator) {
                case '/':
                    if(y == 0) {
                        JOptionPane.showMessageDialog(this, "Cannot Divide By Zero", 
                                "ERROR", JOptionPane.ERROR_MESSAGE);
                    } else {
                        txtInput.setText(String.valueOf(arithmetic.roundOff(x / y)));
                    }
                    break;
                
                case '*':
                    txtInput.setText(String.valueOf(arithmetic.roundOff(x * y)));
                    break;
                
                case '-':
                    txtInput.setText(String.valueOf(arithmetic.roundOff(x - y)));
                    break;
            
                case '+':
                    txtInput.setText(String.valueOf(arithmetic.roundOff(x + y)));
                    break;
            
                case '%':
                    txtInput.setText(String.valueOf((int)(x % y)));
                    break;
                    
                case '^':
                    txtInput.setText(String.valueOf(Math.pow(x, y)));
                    break;
            }
        } catch(HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEqualsActionPerformed

    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        try {
            lblCalculation.setText("sin("+ txtInput.getText() +") =");
            txtInput.setText(String.valueOf(arithmetic.roundOff(Math.sin(Double.parseDouble(
                txtInput.getText())))));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSinActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        try {
            lblCalculation.setText("cos("+ txtInput.getText() +") =");
            txtInput.setText(String.valueOf(arithmetic.roundOff(Math.cos(Double.parseDouble(
                txtInput.getText())))));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        try {
            lblCalculation.setText("tan("+ txtInput.getText() +") =");
            txtInput.setText(String.valueOf(arithmetic.roundOff(Math.tan(Double.parseDouble(
                txtInput.getText())))));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTanActionPerformed

    private void btnSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecActionPerformed
        try {
            lblCalculation.setText("sec("+ txtInput.getText() +") =");
            txtInput.setText(String.valueOf(arithmetic.roundOff(1/Math.cos(Double.parseDouble(
                txtInput.getText())))));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSecActionPerformed

    private void btnCscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCscActionPerformed
        try {
            lblCalculation.setText("csc("+ txtInput.getText() +") =");
            txtInput.setText(String.valueOf(arithmetic.roundOff(1/Math.sin(Double.parseDouble(
                txtInput.getText())))));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCscActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddition;
    private javax.swing.JButton btnClearChar;
    private javax.swing.JButton btnClearEverything;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnCsc;
    private javax.swing.JButton btnCubed;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiplication;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnPoint;
    private javax.swing.JButton btnReciprocal;
    private javax.swing.JButton btnSec;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSigns;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnSquareRoot;
    private javax.swing.JButton btnSquared;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton btnTenPowerX;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnThreeTimesSqrt;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnTwoTimesSqrt;
    private javax.swing.JButton btnXPower;
    private javax.swing.JButton btnZero;
    private javax.swing.JPanel jpButtonPane;
    private javax.swing.JPanel jpDisplayPane;
    private javax.swing.JPanel jpTrigonometryPane;
    private javax.swing.JLabel lblCalculation;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables

}
